services:
  ap-backend:
    build:
      context: .
      dockerfile: ap_backend.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - local
    depends_on:
      - celery

  celery:
    build:
      context: .
      dockerfile: ap_backend_celery.Dockerfile
    ports:
      - "6379:6379"
    networks:
      - local

volumes:
  db_data_ap:
    driver: local

networks:
  local:
    driver: bridge
